### ISSUE TITLE
Roadmap v1

### ISSUE THREAD

**Issue by ThomasBleijendaal** [ThomasBleijendaal/durable-dice#6]
- [x] Display game rules on start page
- [x] Shorten the game id to make sharing more easy
- [ ] When hovering over a field it should highlight its neighbors (allied + enemy)
- [ ] Play sound when your turn
- [ ] Play sounds when rolling and battling
- [x] Do not override rules when players / bots are added
- [x] Allow game rule tweaking on start page
- - [x] Start dice count
- - [x] Dice generation modifier (less players, more growth)
- - [x] Number of dice reallocations per turn
- [x] Add bots
- - [x] Noob bot
- - [x] Medium bot
- - [x] Expert bot
- - [x] Auto-trucing of bots to prevent biggest player of winning easily
- [ ] Improve the graphics
- [x] Test game resume after refresh in Edge
